### PR TITLE
React build

### PR DESCRIPTION
**Pull request by whitneypurdum**
- update React app to use polyfills for server only packages. This requires an extension of webpack using craco.

### CODE REVIEW

**Review by jrhender — DISMISSED** [review]
This look good to me. Perhaps we can add a explain of why the webpack extension is needed and how to do it in the ICL Read the Docs (https://energy-web-foundation-iam-client-lib.readthedocs-hosted.com/#development) and then link to it from iam-client-examples. What do you think of this @whitneypurdum ?

**Review by nichonien — DISMISSED** [review]

**Comment by jrhender** [comment]
@nichonien one question that I have is that the `nest-js` backend app is much less updated than the `express` app. Would that app still need to be updated? I could be done in a separate PR or perhaps we remove the nest-js app, but just curious on what the status is

**Comment by whitneypurdum** [comment]
> This look good to me. Perhaps we can add a explain of why the webpack extension is needed and how to do it in the ICL Read the Docs (https://energy-web-foundation-iam-client-lib.readthedocs-hosted.com/#development) and then link to it from iam-client-examples. What do you think of this @whitneypurdum ?

Sorry, I don't understand what we mean by "how to do it"? Do you want me to explain in the ICL Read The Docs that for React apps that are using Create React App need to use CRACO or React App Rewired to handle WASM and polyfills? And then provide a link?

**Comment by nichonien** [comment]
> @nichonien one question that I have is that the `nest-js` backend app is much less updated than the `express` app. Would that app still need to be updated? I could be done in a separate PR or perhaps we remove the nest-js app, but just curious on what the status is

Hmm, I missed to look at it. Not sure what's the actual use / requirement of nestsJS, but AFAIK very few people use nestJS. Though I could update it in a new PR.

**Comment by nichonien** [comment]
@whitneypurdum Let's not merge this. I'm still getting my expired credentials as verified roles.

**Comment by whitneypurdum** [comment]
> @whitneypurdum Let's not merge this. I'm still getting my expired credentials as verified roles.

@nichonien  Looking through this, I don't see anywhere were the credential's exp is actually being checked? I could be overlooking:
1. [/roles endpoint gets requests user's verified roles from passport did auth](https://github.com/energywebfoundation/iam-client-examples/blob/2bc6388c935b1e9402ef266bc524fed77f742440/server/express/index.js#L30)
2. Passport uses [Login strategy ](https://github.com/energywebfoundation/passport-did-auth/blob/develop/lib/LoginStrategy.ts)to get req.user.verifiedRoles
3. Login strategy calls validate method:
a. [checks for payload](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/ClaimVerifier.ts#L42)
b. checks for DID
c.[ gets all user claims](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/LoginStrategy.ts#L259)
d. Instantiate ClaimVerifier and[ pass each claim to verifyRole method](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/ClaimVerifier.ts#L38)
e. verify that there is a payload
f. [verify there is claim data](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/ClaimVerifier.ts#L49)
g. verify there is a claimTypeVersion
h.Instantiate IssuerVerification from ew credentials and [call verifyIssuer](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/ClaimVerifier.ts#L63) (none of these methods as far as I can see check expiration - exp key)
i. [checkrevocationstatus, verifyIssuer in ew-credentials](https://github.com/energywebfoundation/ew-credentials/blob/f35e9952208487d3ca1ba7505902d8a6d41bcca5/packages/vc-verification/src/verifier/issuer-verification.ts#L72)
j. return roles
k. put roles in local storage
l. react-dapp pulles roles from local storage and displays

I think in this file we need to just add a check on payload.exp and filter for expired. Sorry if I'm overlooking this somewhere! https://github.com/energywebfoundation/passport-did-auth/blob/develop/lib/ClaimVerifier.ts#L38, unless that is happening somewhere in ew-credentials that I'm overlooking.

**Comment by whitneypurdum** [comment]
> > @whitneypurdum Let's not merge this. I'm still getting my expired credentials as verified roles.
> 
> @nichonien Looking through this, I don't see anywhere were the credential's exp is actually being checked? I could be overlooking:
> 
> 1. [/roles endpoint gets requests user's verified roles from passport did auth](https://github.com/energywebfoundation/iam-client-examples/blob/2bc6388c935b1e9402ef266bc524fed77f742440/server/express/index.js#L30)
> 2. Passport uses [Login strategy ](https://github.com/energywebfoundation/passport-did-auth/blob/develop/lib/LoginStrategy.ts)to get req.user.verifiedRoles
> 3. Login strategy calls [validate method](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/LoginStrategy.ts#L202):
>    a. [checks for payload](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/ClaimVerifier.ts#L42)
>    b. checks for DID
>    c.[ gets all user claims](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/LoginStrategy.ts#L259)
>    d. Instantiate ClaimVerifier and[ pass each claim to verifyRole method](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/ClaimVerifier.ts#L38)
>    e. verify that there is a payload
>    f. [verify there is claim data](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/ClaimVerifier.ts#L49)
>    g. verify there is a claimTypeVersion
>    h.Instantiate IssuerVerification from ew credentials and [call verifyIssuer](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/ClaimVerifier.ts#L63) (none of these methods as far as I can see check expiration - exp key)
>    i. [checkrevocationstatus, verifyIssuer in ew-credentials](https://github.com/energywebfoundation/ew-credentials/blob/f35e9952208487d3ca1ba7505902d8a6d41bcca5/packages/vc-verification/src/verifier/issuer-verification.ts#L72)
>    j. return roles
>    k. put roles in local storage
>    l. react-dapp pulles roles from local storage and displays
> 
> I think in this file we need to just add a check on payload.exp and filter for expired. Sorry if I'm overlooking this somewhere! https://github.com/energywebfoundation/passport-did-auth/blob/develop/lib/ClaimVerifier.ts#L38, unless that is happening somewhere in ew-credentials that I'm overlooking. Maybe something like this PR: https://github.com/energywebfoundation/passport-did-auth/pull/326/files

In addition to this, I am also getting back revoked roles in this list (that are not expired) - so I don't think we are filtering for revoked roles either. Should we be doing that?


ّر شيي

**Comment by nichonien** [comment]
> I think in this file we need to just add a check on payload.exp and filter for expired. Sorry if I'm overlooking this somewhere! https://github.com/energywebfoundation/passport-did-auth/blob/develop/lib/ClaimVerifier.ts#L38, unless that is happening somewhere in ew-credentials that I'm overlooking. Maybe something like this PR: https://github.com/energywebfoundation/passport-did-auth/pull/326/files

Thanks @whitneypurdum , I missed to check the expiration of current credentials.

**Comment by nichonien** [comment]
> In addition to this, I am also getting back revoked roles in this list (that are not expired) - so I don't think we are filtering for revoked roles either. Should we be doing that?
> ّر شيي
Yeah, I see that currently there is no validation for the current credentials. Now I feel that `issuer-verification` could have the initial calls for validation of current credential and then the issuer verification or maybe a separate call to verify the current credential. I think this would majorly be covered by use of `iam-client-lib` in `passport-did-auth`. But for now, I will add some revocation check on top of your PR.

**Comment by whitneypurdum** [comment]
> > In addition to this, I am also getting back revoked roles in this list (that are not expired) - so I don't think we are filtering for revoked roles either. Should we be doing that?
> 
> Yeah, I see that currently there is no validation for the current credentials. Now I feel that `issuer-verification` could have the initial calls for validation of current credential and then the issuer verification or maybe a separate call to verify the current credential. I think this would majorly be covered by use of `iam-client-lib` in `passport-did-auth`. But for now, I will add some revocation check on top of your PR.

Yeah, I think the verifyeip191 method in ICL would cover all this. Maybe there’s a reason we don’t use it in passport did auth? I’m not sure.

**Review by JGiter — APPROVED** [review]

**Comment by jrhender** [comment]
> > > @whitneypurdum Let's not merge this. I'm still getting my expired credentials as verified roles.
> > 
> > 
> > @nichonien Looking through this, I don't see anywhere were the credential's exp is actually being checked? I could be overlooking:
> > 
> > 1. [/roles endpoint gets requests user's verified roles from passport did auth](https://github.com/energywebfoundation/iam-client-examples/blob/2bc6388c935b1e9402ef266bc524fed77f742440/server/express/index.js#L30)
> > 2. Passport uses [Login strategy ](https://github.com/energywebfoundation/passport-did-auth/blob/develop/lib/LoginStrategy.ts)to get req.user.verifiedRoles
> > 3. Login strategy calls [validate method](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/LoginStrategy.ts#L202):
> >    a. [checks for payload](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/ClaimVerifier.ts#L42)
> >    b. checks for DID
> >    c.[ gets all user claims](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/LoginStrategy.ts#L259)
> >    d. Instantiate ClaimVerifier and[ pass each claim to verifyRole method](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/ClaimVerifier.ts#L38)
> >    e. verify that there is a payload
> >    f. [verify there is claim data](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/ClaimVerifier.ts#L49)
> >    g. verify there is a claimTypeVersion
> >    h.Instantiate IssuerVerification from ew credentials and [call verifyIssuer](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/ClaimVerifier.ts#L63) (none of these methods as far as I can see check expiration - exp key)
> >    i. [checkrevocationstatus, verifyIssuer in ew-credentials](https://github.com/energywebfoundation/ew-credentials/blob/f35e9952208487d3ca1ba7505902d8a6d41bcca5/packages/vc-verification/src/verifier/issuer-verification.ts#L72)
> >    j. return roles
> >    k. put roles in local storage
> >    l. react-dapp pulles roles from local storage and displays
> > 
> > I think in this file we need to just add a check on payload.exp and filter for expired. Sorry if I'm overlooking this somewhere! https://github.com/energywebfoundation/passport-did-auth/blob/develop/lib/ClaimVerifier.ts#L38, unless that is happening somewhere in ew-credentials that I'm overlooking. Maybe something like this PR: https://github.com/energywebfoundation/passport-did-auth/pull/326/files
> 
> In addition to this, I am also getting back revoked roles in this list (that are not expired) - so I don't think we are filtering for revoked roles either. Should we be doing that?
> 

@whitneypurdum could you test the behaviour of revoked roles again when you have a moment please 🙇 ?

**Comment by whitneypurdum** [comment]
> > > > @whitneypurdum Let's not merge this. I'm still getting my expired credentials as verified roles.
> > > 
> > > 
> > > @nichonien Looking through this, I don't see anywhere were the credential's exp is actually being checked? I could be overlooking:
> > > 
> > > 1. [/roles endpoint gets requests user's verified roles from passport did auth](https://github.com/energywebfoundation/iam-client-examples/blob/2bc6388c935b1e9402ef266bc524fed77f742440/server/express/index.js#L30)
> > > 2. Passport uses [Login strategy ](https://github.com/energywebfoundation/passport-did-auth/blob/develop/lib/LoginStrategy.ts)to get req.user.verifiedRoles
> > > 3. Login strategy calls [validate method](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/LoginStrategy.ts#L202):
> > >    a. [checks for payload](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/ClaimVerifier.ts#L42)
> > >    b. checks for DID
> > >    c.[ gets all user claims](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/LoginStrategy.ts#L259)
> > >    d. Instantiate ClaimVerifier and[ pass each claim to verifyRole method](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/ClaimVerifier.ts#L38)
> > >    e. verify that there is a payload
> > >    f. [verify there is claim data](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/ClaimVerifier.ts#L49)
> > >    g. verify there is a claimTypeVersion
> > >    h.Instantiate IssuerVerification from ew credentials and [call verifyIssuer](https://github.com/energywebfoundation/passport-did-auth/blob/acacac6bb79cda91ff5cb21191b4197e351200c7/lib/ClaimVerifier.ts#L63) (none of these methods as far as I can see check expiration - exp key)
> > >    i. [checkrevocationstatus, verifyIssuer in ew-credentials](https://github.com/energywebfoundation/ew-credentials/blob/f35e9952208487d3ca1ba7505902d8a6d41bcca5/packages/vc-verification/src/verifier/issuer-verification.ts#L72)
> > >    j. return roles
> > >    k. put roles in local storage
> > >    l. react-dapp pulles roles from local storage and displays
> > > 
> > > I think in this file we need to just add a check on payload.exp and filter for expired. Sorry if I'm overlooking this somewhere! https://github.com/energywebfoundation/passport-did-auth/blob/develop/lib/ClaimVerifier.ts#L38, unless that is happening somewhere in ew-credentials that I'm overlooking. Maybe something like this PR: https://github.com/energywebfoundation/passport-did-auth/pull/326/files
> > 
> > 
> > In addition to this, I am also getting back revoked roles in this list (that are not expired) - so I don't think we are filtering for revoked roles either. Should we be doing that?
> 
> @whitneypurdum could you test the behaviour of revoked roles again when you have a moment please 🙇 ?

Sure thing @jrhender. Just tested, I just see two small discrepencies with 'My Enrolments' (that are accepted, not revoked, not expired) in SB:
1. This role is not showing up at all in IAM Client examples, but shows up in 'My Enrolments. Maybe this role doesn't 'exist' anymore as Florin is gone? 
Screen Shot 2022-09-07 at 10 57 13 AM

2. One role that is revoked ON CHAIN, but is not revoked OFF CHAIN is showing up in my iam-client-examples roles. This could be correct behavior, but just mentioning here.

**Comment by nichonien** [comment]
> 1. This role is not showing up at all in IAM Client examples, but shows up in 'My Enrolments. Maybe this role doesn't 'exist' anymore as Florin is gone?
>    Screen Shot 2022-09-07 at 10 57 13 AM

If the issuer's credential has been revoked or expired then this wouldn't come. Both holder's and issuer's credential needs to be valid to be verified.

> 2. One role that is revoked ON CHAIN, but is not revoked OFF CHAIN is showing up in my iam-client-examples roles. This could be correct behavior, but just mentioning here.

This is expected since the roles are verified only for off-chain issuance. So if anything is revoked on-chain, it wouldn't reflect.

**Comment by whitneypurdum** [comment]
> @whitneypurdum
> 
> > 1. This role is not showing up at all in IAM Client examples, but shows up in 'My Enrolments. Maybe this role doesn't 'exist' anymore as Florin is gone?
> >    Screen Shot 2022-09-07 at 10 57 13 AM
> 
> If the issuer's credential has been revoked or expired then this wouldn't come. Both holder's and issuer's credential needs to be valid to be verified.
> 
> > 2. One role that is revoked ON CHAIN, but is not revoked OFF CHAIN is showing up in my iam-client-examples roles. This could be correct behavior, but just mentioning here.
> 
> This is expected since the roles are verified only for off-chain issuance. So if anything is revoked on-chain, it wouldn't reflect.

Oh great! I think it’s all good then!

**Review by nichonien — APPROVED** [review]

**Pull request merged**
