### PR TITLE
fix(angular): loader color

### PR DESCRIPTION
**Pull request by dawidgil**

### CODE REVIEW

**Comment by jrhender** [comment]
@dawidgil spinner colour looks good. How hard is it to change the inner colour from white to a similar blue as the general page background 
image

**Comment by dawidgil** [comment]
@jrhender background is an image, so i can't set the same colour. I can pick something that is similar if that is ok for you (transparent won't work 😞  ).

**Comment by dawidgil** [comment]
image
is it ok?

**Comment by jrhender** [comment]
@dawidgil  Perfect, thanks

**Review by jrhender — APPROVED** [review]

**Review by nichonien — APPROVED** [review]

**Pull request merged**
